# Используйте официальный образ PostgreSQL
FROM postgres:latest

# Настройте переменные окружения для пользователя, пароля и имени базы данных
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=node_postgres

# Добавьте дополнительные инструкции по настройке вашей базы данных, если необходимо